// Command xhup_aux generates the shape-code dictionary used by the
// double_pinyin_flypy schema's backtick auxiliary filter.
//
// Run from others/script:
//
//	go run ./xhup_aux
//
// It scans every xhup_dicts/*.yaml entry, keeps single Han characters with a
// four-letter Xiaohe code, and removes the first two phonetic letters. The
// remaining two letters are the Xiaohe shape code (e.g. anfn -> fn).
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"
)

func main() {
	root := flag.String("root", "../..", "repository root")
	output := flag.String("output", "../../xhup_aux.dict.yaml", "generated dictionary path")
	flag.Parse()

	files, err := filepath.Glob(filepath.Join(*root, "xhup_dicts", "*.yaml"))
	check(err)
	if len(files) == 0 {
		fatalf("no xhup dictionary files found under %s", *root)
	}

	entries := make(map[string]map[string]struct{})
	for _, path := range files {
		readDictionary(path, entries)
	}

	characters := make([]string, 0, len(entries))
	for character := range entries {
		characters = append(characters, character)
	}
	sort.Strings(characters)

	f, err := os.Create(*output)
	check(err)
	w := bufio.NewWriter(f)
	fmt.Fprint(w, `# Rime dictionary
# encoding: utf-8
#
# Generated by: cd others/script && go run ./xhup_aux
# Do not edit entries manually. The generator scans xhup_dicts/*.yaml, keeps
# single Han characters with four-letter codes, and strips the first two
# phonetic letters to retain the two-letter Xiaohe shape code.
# Used by double_pinyin_flypy.schema.yaml after the backtick search key.

---
name: xhup_aux
version: "10.9"
sort: original
use_preset_vocabulary: false
...
`)

	entryCount := 0
	for _, character := range characters {
		codes := make([]string, 0, len(entries[character]))
		for code := range entries[character] {
			codes = append(codes, code)
		}
		sort.Strings(codes)
		for _, code := range codes {
			fmt.Fprintf(w, "%s\t%s\n", character, code)
			entryCount++
		}
	}

	check(w.Flush())
	check(f.Close())
	fmt.Printf("generated %s: %d characters, %d entries\n", *output, len(characters), entryCount)
}

func readDictionary(path string, entries map[string]map[string]struct{}) {
	f, err := os.Open(path)
	check(err)
	defer f.Close()

	scanner := bufio.NewScanner(f)
	// Some dictionaries contain long phrase lines. Leave enough room to scan
	// them even though only single-character entries are retained.
	scanner.Buffer(make([]byte, 64*1024), 1024*1024)
	for scanner.Scan() {
		line := strings.TrimSuffix(strings.TrimPrefix(scanner.Text(), "\ufeff"), "\r")
		fields := strings.Split(line, "\t")
		if len(fields) < 2 {
			continue
		}

		character, code := fields[0], strings.TrimSpace(fields[1])
		r, size := utf8.DecodeRuneInString(character)
		if r == utf8.RuneError || size != len(character) || !unicode.Is(unicode.Han, r) || !isFourLetterCode(code) {
			continue
		}

		shapeCode := code[2:]
		if entries[character] == nil {
			entries[character] = make(map[string]struct{})
		}
		entries[character][shapeCode] = struct{}{}
	}
	check(scanner.Err())
}

func isFourLetterCode(code string) bool {
	if len(code) != 4 {
		return false
	}
	for _, c := range code {
		if c < 'a' || c > 'z' {
			return false
		}
	}
	return true
}

func check(err error) {
	if err != nil {
		fatalf("%v", err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "xhup_aux: "+format+"\n", args...)
	os.Exit(1)
}
